"""Modify document table

Revision ID: 24238f2c5e88
Revises: fcdcb9bc5820
Create Date: 2025-11-22 09:28:28.968754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24238f2c5e88'
down_revision: Union[str, Sequence[str], None] = 'fcdcb9bc5820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
