"""Create users table

Revision ID: 4a844fd6747b
Revises: 03382600a148
Create Date: 2025-11-28 08:44:09.869329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '4a844fd6747b'
down_revision: Union[str, Sequence[str], None] = '03382600a148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'documentstatusenum', ['PENDING', 'INDEXING', 'INDEXED', 'FAILED', 'PARSING'],
                        [TableReference(table_schema='public', table_name='documents', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'documentstatusenum', ['PENDING', 'INDEXING', 'INDEXED', 'FAILED'],
                        [TableReference(table_schema='public', table_name='documents', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
