"""Optional chunk index

Revision ID: 5013b93373a7
Revises: 4a844fd6747b
Create Date: 2025-11-28 09:26:46.562577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5013b93373a7'
down_revision: Union[str, Sequence[str], None] = '4a844fd6747b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
