"""add_thread_feedback

Revision ID: 501858083ce7
Revises: 2e6e57d0e4bf
Create Date: 2026-06-29 05:54:32.917936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501858083ce7'
down_revision: Union[str, Sequence[str], None] = '2e6e57d0e4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('is_understandable', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_feedbacks_id'), 'thread_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_thread_feedbacks_thread_id'), 'thread_feedbacks', ['thread_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_feedbacks_thread_id'), table_name='thread_feedbacks')
    op.drop_index(op.f('ix_thread_feedbacks_id'), table_name='thread_feedbacks')
    op.drop_table('thread_feedbacks')
    # ### end Alembic commands ###
