"""Remove chunk_metadata

Revision ID: 781f1368cba8
Revises: d6fed0fce794
Create Date: 2025-11-22 10:19:29.940931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '781f1368cba8'
down_revision: Union[str, Sequence[str], None] = 'd6fed0fce794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'INDEXING', 'INDEXED', 'FAILED', name='documentstatusenum').create(op.get_bind())
    op.add_column('documents', sa.Column('status', postgresql.ENUM('PENDING', 'INDEXING', 'INDEXED', 'FAILED', name='documentstatusenum', create_type=False), nullable=False))
    op.drop_column('messages', 'chunk_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('documents', 'status')
    sa.Enum('PENDING', 'INDEXING', 'INDEXED', 'FAILED', name='documentstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
