"""Update StatusEnum of document

Revision ID: a38f1e2f448d
Revises: 590c23c3a17b
Create Date: 2025-12-05 17:22:58.796600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a38f1e2f448d'
down_revision: Union[str, Sequence[str], None] = '590c23c3a17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'documentstatusenum', ['PENDING', 'PARSING', 'READY', 'INDEXING', 'INDEXED', 'PARSING_FAILED', 'CHUNKING_FAILED'],
                        [TableReference(table_schema='public', table_name='documents', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'documentstatusenum', ['PENDING', 'PARSING', 'READY', 'INDEXING', 'INDEXED', 'PARSING_FAILED', 'INDEXING_FAILED'],
                        [TableReference(table_schema='public', table_name='documents', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
