"""Update user to UUID instead

Revision ID: fa9a335d5e77
Revises: 7abfdad2622c
Create Date: 2025-11-21 13:17:18.175929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'fa9a335d5e77'
down_revision: Union[str, Sequence[str], None] = '7abfdad2622c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable uuid-ossp extension if not already enabled
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # Add a temporary UUID column
    op.add_column('users', sa.Column('new_id', sa.dialects.postgresql.UUID(), nullable=True))
    
    # Generate UUIDs for existing rows
    op.execute('UPDATE users SET new_id = uuid_generate_v4()')
    
    # Make the new_id column non-nullable
    op.alter_column('users', 'new_id', nullable=False)
    
    # Drop the old id column and rename new_id to id
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.drop_column('users', 'id')
    op.alter_column('users', 'new_id', new_column_name='id')
    
    # Re-create primary key constraint
    op.create_primary_key('users_pkey', 'users', ['id'])
    
    # Re-create index
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # Update enum to include MODERATOR
    op.sync_enum_values(
        enum_schema='public',
        enum_name='roleenum',
        new_values=['ADMIN', 'MODERATOR', 'USER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert enum changes first
    op.sync_enum_values(
        enum_schema='public',
        enum_name='roleenum',
        new_values=['ADMIN', 'USER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    
    # Add a temporary integer column
    op.add_column('users', sa.Column('new_id', sa.INTEGER(), nullable=True))
    
    # Generate sequential IDs for existing rows
    op.execute('UPDATE users SET new_id = ROW_NUMBER() OVER (ORDER BY id)')
    
    # Make the new_id column non-nullable
    op.alter_column('users', 'new_id', nullable=False)
    
    # Drop the old UUID id column and rename new_id to id
    op.drop_constraint('users_pkey', 'users', type_='primary')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'id')
    op.alter_column('users', 'new_id', new_column_name='id')
    
    # Re-create primary key constraint and index
    op.create_primary_key('users_pkey', 'users', ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
